---
# tasks file for ansible-role-docker
- name: Load var files
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - main.yml
      paths:
        - "{{ role_path }}/vars"

- name: Install pre-requisites
  tags:
    - "{{ role_tags }}"
  become: true
  become_user: root
  block:
    - name: Update apt repositories
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ required_packages }}"
        state: present

- name: Pre-installation checks
  tags:
    - "{{ role_tags }}"
  become: true
  become_user: root
  block:
    - name: Check if docker.sources file exists
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/docker.sources
      register: docker_sources_file

    - name: Remove all conflicting packages
      ansible.builtin.apt:
        name: "{{ remove_docker_packages }}"
        state: absent
      when: not docker_sources_file.stat.exists

- name: Set up Docker's repository and Install Docker
  tags:
    - "{{ role_tags }}"
  become: true
  become_user: root
  block:
    - name: Get platform architecture
      ansible.builtin.command: dpkg --print-architecture
      register: system_architecture
      changed_when: false

    - name: Set up Docker's apt repository
      ansible.builtin.deb822_repository:
        name: docker
        suites: "{{ ansible_distribution_release }}"
        types: deb
        components: stable
        architectures: "{{ system_architecture.stdout }}"
        uris: https://download.docker.com/linux/{{ ansible_distribution | lower }}
        signed_by: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg

    - name: Update apt sources
      ansible.builtin.apt:
        update_cache: true

    - name: Install the Docker packages
      ansible.builtin.apt:
        name: "{{ install_docker_packages }}"
        state: present

    - name: Add current user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
